# Generated by Django 3.1.5 on 2021-02-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsapp', '0002_auto_20210208_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.CharField(max_length=255),
        ),
    ]
